/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.EmergencyWorkArea;

import Business.DischargedPatient.DischargedPatient;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neelu
 */
public class MedicalRecordJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DischargedPatient dischargedPatient;
    
    /**
     * Creates new form MedicalRecordJPanel
     */
    public MedicalRecordJPanel(JPanel upc, DischargedPatient dp) {
        initComponents();
        userProcessContainer = upc;
         dischargedPatient = dp;
         
         populateTable();
    }
    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel)medicalTable.getModel();
        
        int rowcount = medicalTable.getRowCount();
        
        for(int i =rowcount-1;i>=0;i--){
        dtm.removeRow(i);
    }
        Object row[] = new Object[10];
            row[0]= dischargedPatient.getMedicalRecord().getAbuseFactor();
            row[1]= dischargedPatient.getMedicalRecord().getTreatedFor();
            row[2]= dischargedPatient.getMedicalRecord().getAllergies();
            row[3]=dischargedPatient.getMedicalRecord().getFeedingStatus();
            row[4]=dischargedPatient.getMedicalRecord().getFoodIntake();
            row[5]=dischargedPatient.getMedicalRecord().getSpecialNeeds();
            row[6]=dischargedPatient.getMedicalRecord().getAminoAcid();
            row[7]=dischargedPatient.getMedicalRecord().getFatEmulsion();
            row[8]=dischargedPatient.getMedicalRecord().getProtienIntake();
            row[9]=dischargedPatient.getMedicalRecord().getMedicinePrescribed();
            dtm.addRow(row);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicalTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Display Medical Record");

        medicalTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        medicalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Abuse Factor", "Treated For", "Allergy", "Feeding Status", "Food Intake", "Special Needs", "Amino Acid", "Fat Emulsion", "Protein Intake", "Medicine Prescribed"
            }
        ));
        jScrollPane1.setViewportView(medicalTable);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("<<Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(119, 119, 119))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicalTable;
    // End of variables declaration//GEN-END:variables
}
