/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.EmergencyWorkArea;

import Business.DischargedPatient.DischargedPatient;
import Business.VitalSign.VitalSign;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neelu
 */
public class VitalSignJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    
    private DischargedPatient dischargedPatient;
    
    /**
     * Creates new form VitalSignJPanel
     */
    public VitalSignJPanel(JPanel upc, DischargedPatient dp ) {
        initComponents();
        userProcessContainer = upc;
        
        dischargedPatient = dp;
        
        populateVitalSignTable();
    }

    public void populateVitalSignTable(){
        
         DefaultTableModel dtm = (DefaultTableModel)vitalSignTable.getModel();
        
        int rowcount = vitalSignTable.getRowCount();
       
        
        for(int i =rowcount-1;i>=0;i--){
        dtm.removeRow(i);
    }
         
         
        for(VitalSign vitalSign:dischargedPatient.getVitalSignHistory().getVitalSignList()){
            Object row[] = new Object[6];
            row[0]= vitalSign.getTimestamp();
            row[1]= vitalSign.getStatusReport();
            row[2]= vitalSign.getHeartRate();
            row[3]=vitalSign.getBloodPressure();
            row[4]=vitalSign.getWeight();
            row[5]=vitalSign.getRespiratoryRate();
            dtm.addRow(row);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        vitalSignTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Check Vital Signs");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        vitalSignTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vitalSignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TimeStamp", "Vital Sign Status", "Heart Rate", "Blood Pressure", "Weight", "Respiratory Rate"
            }
        ));
        jScrollPane3.setViewportView(vitalSignTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 1150, 170));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("IOT Devices Capturing Vital Signs");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 193, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("<<Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable vitalSignTable;
    // End of variables declaration//GEN-END:variables
}
