/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReceptionistWorkArea;

import Business.DischargedPatient.DischargedPatient;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Organization.ReceptionistOrganization;
import Business.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neelu
 */
public class DischargePatientJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private ReceptionistOrganization receptionistOrganization;
    private UserAccount userAccount;
    
            
    /**
     * Creates new form DischargePatientJPanel
     */
    public DischargePatientJPanel(JPanel upc, UserAccount ua, ReceptionistOrganization ro, Enterprise e) {
        initComponents();
        userProcessContainer = upc;
        userAccount = ua;
        receptionistOrganization =ro;
        enterprise = e;
        
        populateTable();
        
    }
    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel)patientDatabase.getModel();
        
        int rowcount = patientDatabase.getRowCount();
        
        for(int i =rowcount-1;i>=0;i--){
        dtm.removeRow(i);
    }
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PatientOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            for(Employee patient: org.getEmployeeDirectory().getEmployeeList()){
                Object row[] = new Object[8];
                row[0]= patient;
                row[1]= patient.getPrimaryDoctor();
                row[2] =patient.getMedicalRecord().getAdmissionDate();
                row[3] = patient.getMedicalRecord().getResumeWork();
                row[4] = patient.getMedicalRecord().getIsOperationPerformed();
                row[5] = patient.getMedicalRecord().getTreatedFor();
                row[6] = patient.getMedicalRecord().getDischarge()== null ? "Not Yet" : patient.getMedicalRecord().getDischarge();
                row[7] = patient.getMedicalRecord().getDischargeDate() == null ? "Not Yet" : patient.getMedicalRecord().getDischargeDate();
                dtm.addRow(row);
            }
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientDatabase = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Discharge Patient");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 16, -1, -1));

        patientDatabase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        patientDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Doctor Name", "Admission Date", "Resume Work", "Is Operation Performed", "Treated For", "Discharge", "Discharge Date"
            }
        ));
        jScrollPane1.setViewportView(patientDatabase);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 169, 1093, 117));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Dischage and Update Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("<<Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Check Patient's Records");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = patientDatabase.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a Row!");
            return;
        }
        
        Employee patient = (Employee) patientDatabase.getValueAt(selectedRow, 0);
        
        Date date = new Date();
        patient.getMedicalRecord().setDischarge("Yes");
        patient.getMedicalRecord().setDischargeDate(date);
        
        DischargedPatient dispat = enterprise.getDischargedPatientDirectory().createPatient();
        dispat.setPatientName(patient.getName());
        dispat.setAge(patient.getAge());
        dispat.setPatientId(Integer.toString(patient.getId()));
        dispat.setPrimaryDoctor(patient.getPrimaryDoctor());
        dispat.setMedicalRecord(patient.getMedicalRecord());
        
        
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientDatabase;
    // End of variables declaration//GEN-END:variables
}
